// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spacemeshos/go-spacemesh/vm/core (interfaces: Template)
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/template.go github.com/spacemeshos/go-spacemesh/vm/core Template
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplate is a mock of Template interface.
type MockTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateMockRecorder
	isgomock struct{}
}

// MockTemplateMockRecorder is the mock recorder for MockTemplate.
type MockTemplateMockRecorder struct {
	mock *MockTemplate
}

// NewMockTemplate creates a new mock instance.
func NewMockTemplate(ctrl *gomock.Controller) *MockTemplate {
	mock := &MockTemplate{ctrl: ctrl}
	mock.recorder = &MockTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplate) EXPECT() *MockTemplateMockRecorder {
	return m.recorder
}

// BaseGas mocks base method.
func (m *MockTemplate) BaseGas() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseGas")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// BaseGas indicates an expected call of BaseGas.
func (mr *MockTemplateMockRecorder) BaseGas() *MockTemplateBaseGasCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseGas", reflect.TypeOf((*MockTemplate)(nil).BaseGas))
	return &MockTemplateBaseGasCall{Call: call}
}

// MockTemplateBaseGasCall wrap *gomock.Call
type MockTemplateBaseGasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateBaseGasCall) Return(arg0 uint64) *MockTemplateBaseGasCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateBaseGasCall) Do(f func() uint64) *MockTemplateBaseGasCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateBaseGasCall) DoAndReturn(f func() uint64) *MockTemplateBaseGasCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadGas mocks base method.
func (m *MockTemplate) LoadGas() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGas")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// LoadGas indicates an expected call of LoadGas.
func (mr *MockTemplateMockRecorder) LoadGas() *MockTemplateLoadGasCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGas", reflect.TypeOf((*MockTemplate)(nil).LoadGas))
	return &MockTemplateLoadGasCall{Call: call}
}

// MockTemplateLoadGasCall wrap *gomock.Call
type MockTemplateLoadGasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateLoadGasCall) Return(arg0 uint64) *MockTemplateLoadGasCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateLoadGasCall) Do(f func() uint64) *MockTemplateLoadGasCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateLoadGasCall) DoAndReturn(f func() uint64) *MockTemplateLoadGasCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Verify mocks base method.
func (m *MockTemplate) Verify(tx, witnessData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", tx, witnessData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockTemplateMockRecorder) Verify(tx, witnessData any) *MockTemplateVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTemplate)(nil).Verify), tx, witnessData)
	return &MockTemplateVerifyCall{Call: call}
}

// MockTemplateVerifyCall wrap *gomock.Call
type MockTemplateVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateVerifyCall) Return(arg0 error) *MockTemplateVerifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateVerifyCall) Do(f func([]byte, []byte) error) *MockTemplateVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateVerifyCall) DoAndReturn(f func([]byte, []byte) error) *MockTemplateVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
