// Code generated by protoc-gen-go. DO NOT EDIT.
// source: handshake.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	handshake.proto

It has these top-level messages:
	HandshakeData
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// used for both request and response
type HandshakeData struct {
	NodePubKey []byte `protobuf:"bytes,1,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Iv         []byte `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	SharedKey  []byte `protobuf:"bytes,3,opt,name=sharedKey,proto3" json:"sharedKey,omitempty"`
	Hmac       []byte `protobuf:"bytes,4,opt,name=hmac,proto3" json:"hmac,omitempty"`
	Sign       string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
}

func (m *HandshakeData) Reset()                    { *m = HandshakeData{} }
func (m *HandshakeData) String() string            { return proto.CompactTextString(m) }
func (*HandshakeData) ProtoMessage()               {}
func (*HandshakeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HandshakeData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *HandshakeData) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *HandshakeData) GetSharedKey() []byte {
	if m != nil {
		return m.SharedKey
	}
	return nil
}

func (m *HandshakeData) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

func (m *HandshakeData) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func init() {
	proto.RegisterType((*HandshakeData)(nil), "pb.HandshakeData")
}

func init() { proto.RegisterFile("handshake.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0xcc, 0x4b,
	0x29, 0xce, 0x48, 0xcc, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x6a, 0x65, 0xe4, 0xe2, 0xf5, 0x80, 0x89, 0xbb, 0x24, 0x96, 0x24, 0x0a, 0xc9, 0x71, 0x71, 0xe5,
	0xe5, 0xa7, 0xa4, 0x06, 0x94, 0x26, 0x79, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04,
	0x21, 0x89, 0x08, 0xf1, 0x71, 0x31, 0x65, 0x96, 0x49, 0x30, 0x81, 0xc5, 0x99, 0x32, 0xcb, 0x84,
	0x64, 0xb8, 0x38, 0x8b, 0x33, 0x12, 0x8b, 0x52, 0x53, 0x40, 0xca, 0x99, 0xc1, 0xc2, 0x08, 0x01,
	0x21, 0x21, 0x2e, 0x96, 0x8c, 0xdc, 0xc4, 0x64, 0x09, 0x16, 0xb0, 0x04, 0x98, 0x0d, 0x12, 0x2b,
	0xce, 0x4c, 0xcf, 0x93, 0x60, 0x55, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x9d, 0x58, 0xa2, 0x98,
	0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x0e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x8b, 0x5c,
	0x3d, 0xab, 0x00, 0x00, 0x00,
}
