// Code generated by protoc-gen-go. DO NOT EDIT.
// source: handshake.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	handshake.proto

It has these top-level messages:
	CommonMessageData
	HandshakeData
	ProtocolMessage
	Metadata
	PingReqData
	PongRespData
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// data common to all messages - Top level msg format
type CommonMessageData struct {
	SessionId []byte `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *CommonMessageData) Reset()                    { *m = CommonMessageData{} }
func (m *CommonMessageData) String() string            { return proto.CompactTextString(m) }
func (*CommonMessageData) ProtoMessage()               {}
func (*CommonMessageData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommonMessageData) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *CommonMessageData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Handshake protocol data used for both request and response - sent unencrypted on the wire
type HandshakeData struct {
	SessionId  []byte `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Payload    []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Protocol   string `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	NodePubKey []byte `protobuf:"bytes,4,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Iv         []byte `protobuf:"bytes,5,opt,name=iv,proto3" json:"iv,omitempty"`
	PubKey     []byte `protobuf:"bytes,6,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Hmac       []byte `protobuf:"bytes,7,opt,name=hmac,proto3" json:"hmac,omitempty"`
	TcpAddress string `protobuf:"bytes,8,opt,name=tcpAddress" json:"tcpAddress,omitempty"`
	Sign       string `protobuf:"bytes,9,opt,name=sign" json:"sign,omitempty"`
}

func (m *HandshakeData) Reset()                    { *m = HandshakeData{} }
func (m *HandshakeData) String() string            { return proto.CompactTextString(m) }
func (*HandshakeData) ProtoMessage()               {}
func (*HandshakeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HandshakeData) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *HandshakeData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *HandshakeData) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *HandshakeData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *HandshakeData) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *HandshakeData) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *HandshakeData) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

func (m *HandshakeData) GetTcpAddress() string {
	if m != nil {
		return m.TcpAddress
	}
	return ""
}

func (m *HandshakeData) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

// used for protocol messages (non-handshake) - this is the decrypted CommonMessageData.payload
// it allows multiplexing back to higher level protocol
// data is here and not in CommonMessageData to limit leaked data on unencrypted connections
type ProtocolMessage struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *ProtocolMessage) Reset()                    { *m = ProtocolMessage{} }
func (m *ProtocolMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolMessage) ProtoMessage()               {}
func (*ProtocolMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtocolMessage) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Metadata struct {
	Protocol      string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	ReqId         []byte `protobuf:"bytes,2,opt,name=reqId,proto3" json:"reqId,omitempty"`
	ClientVersion string `protobuf:"bytes,3,opt,name=clientVersion" json:"clientVersion,omitempty"`
	Timestamp     int64  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Gossip        bool   `protobuf:"varint,5,opt,name=gossip" json:"gossip,omitempty"`
	AuthPubKey    []byte `protobuf:"bytes,6,opt,name=authPubKey,proto3" json:"authPubKey,omitempty"`
	AuthorSign    string `protobuf:"bytes,7,opt,name=authorSign" json:"authorSign,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Metadata) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Metadata) GetReqId() []byte {
	if m != nil {
		return m.ReqId
	}
	return nil
}

func (m *Metadata) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *Metadata) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Metadata) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *Metadata) GetAuthPubKey() []byte {
	if m != nil {
		return m.AuthPubKey
	}
	return nil
}

func (m *Metadata) GetAuthorSign() string {
	if m != nil {
		return m.AuthorSign
	}
	return ""
}

// example protocol
type PingReqData struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Ping     string    `protobuf:"bytes,2,opt,name=ping" json:"ping,omitempty"`
}

func (m *PingReqData) Reset()                    { *m = PingReqData{} }
func (m *PingReqData) String() string            { return proto.CompactTextString(m) }
func (*PingReqData) ProtoMessage()               {}
func (*PingReqData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PingReqData) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PingReqData) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type PongRespData struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Pong     string    `protobuf:"bytes,2,opt,name=pong" json:"pong,omitempty"`
}

func (m *PongRespData) Reset()                    { *m = PongRespData{} }
func (m *PongRespData) String() string            { return proto.CompactTextString(m) }
func (*PongRespData) ProtoMessage()               {}
func (*PongRespData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PongRespData) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PongRespData) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonMessageData)(nil), "pb.CommonMessageData")
	proto.RegisterType((*HandshakeData)(nil), "pb.HandshakeData")
	proto.RegisterType((*ProtocolMessage)(nil), "pb.ProtocolMessage")
	proto.RegisterType((*Metadata)(nil), "pb.Metadata")
	proto.RegisterType((*PingReqData)(nil), "pb.PingReqData")
	proto.RegisterType((*PongRespData)(nil), "pb.PongRespData")
}

func init() { proto.RegisterFile("handshake.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x8a, 0xdb, 0x30,
	0x10, 0xc7, 0xb1, 0xf3, 0x65, 0x4f, 0x92, 0x86, 0x8a, 0x52, 0x44, 0x29, 0x25, 0x98, 0x1e, 0x72,
	0xca, 0xa1, 0x3d, 0xf6, 0xd4, 0x8f, 0x43, 0x43, 0x36, 0x60, 0xbc, 0xb0, 0x87, 0xbd, 0xc9, 0xb6,
	0xb0, 0xc5, 0xc6, 0x92, 0x62, 0x29, 0x81, 0xbc, 0xe9, 0xbe, 0xc7, 0xbe, 0xc0, 0xa2, 0x89, 0x9d,
	0x38, 0x7b, 0x5a, 0x76, 0x6f, 0x33, 0xbf, 0x89, 0xfe, 0xd2, 0xfc, 0x62, 0x98, 0x95, 0x4c, 0xe6,
	0xa6, 0x64, 0x0f, 0x7c, 0xa9, 0x6b, 0x65, 0x15, 0xf1, 0x75, 0x1a, 0xad, 0xe1, 0xe3, 0x5f, 0x55,
	0x55, 0x4a, 0x6e, 0xb8, 0x31, 0xac, 0xe0, 0xff, 0x98, 0x65, 0xe4, 0x2b, 0x84, 0x86, 0x1b, 0x23,
	0x94, 0x5c, 0xe5, 0xd4, 0x9b, 0x7b, 0x8b, 0x49, 0x72, 0x01, 0x84, 0xc2, 0x48, 0xb3, 0xe3, 0x56,
	0xb1, 0x9c, 0xfa, 0x38, 0x6b, 0xdb, 0xe8, 0xc9, 0x83, 0xe9, 0xff, 0xf6, 0x92, 0xf7, 0x24, 0x91,
	0x2f, 0x10, 0xe0, 0x1b, 0x33, 0xb5, 0xa5, 0xbd, 0xb9, 0xb7, 0x08, 0x93, 0x73, 0x4f, 0xbe, 0x01,
	0x48, 0x95, 0xf3, 0x78, 0x9f, 0xae, 0xf9, 0x91, 0xf6, 0xf1, 0x60, 0x87, 0x90, 0x0f, 0xe0, 0x8b,
	0x03, 0x1d, 0x20, 0xf7, 0xc5, 0x81, 0x7c, 0x86, 0xa1, 0x3e, 0xfd, 0x76, 0x88, 0xac, 0xe9, 0x08,
	0x81, 0x7e, 0x59, 0xb1, 0x8c, 0x8e, 0x90, 0x62, 0xed, 0xb2, 0x6d, 0xa6, 0x7f, 0xe7, 0x79, 0xcd,
	0x8d, 0xa1, 0x01, 0xde, 0xdc, 0x21, 0xee, 0x8c, 0x11, 0x85, 0xa4, 0x21, 0x4e, 0xb0, 0x8e, 0x7e,
	0xc1, 0x2c, 0x6e, 0xde, 0xd6, 0x48, 0x24, 0x0b, 0x08, 0x2a, 0x6e, 0x59, 0xce, 0x2c, 0xc3, 0xad,
	0xc7, 0x3f, 0x26, 0x4b, 0x9d, 0x2e, 0x37, 0x0d, 0x4b, 0xce, 0xd3, 0xe8, 0xd1, 0x83, 0xa0, 0xc5,
	0x57, 0x5b, 0x7b, 0x2f, 0xb6, 0xfe, 0x04, 0x83, 0x9a, 0xef, 0x56, 0xad, 0xa9, 0x53, 0x43, 0xbe,
	0xc3, 0x34, 0xdb, 0x0a, 0x2e, 0xed, 0x1d, 0xaf, 0x9d, 0xd4, 0x46, 0xd6, 0x35, 0x74, 0xff, 0x82,
	0x15, 0x15, 0x37, 0x96, 0x55, 0x1a, 0x85, 0xf5, 0x92, 0x0b, 0x70, 0x7e, 0x0a, 0x65, 0x8c, 0xd0,
	0xe8, 0x2c, 0x48, 0x9a, 0xce, 0xb9, 0x60, 0x7b, 0x5b, 0xc6, 0x5d, 0x77, 0x1d, 0xd2, 0xce, 0x55,
	0x7d, 0xeb, 0x8c, 0x8c, 0x4e, 0xae, 0x2e, 0x24, 0x5a, 0xc3, 0x38, 0x16, 0xb2, 0x48, 0xf8, 0x0e,
	0x3f, 0x85, 0x57, 0x3b, 0x71, 0x92, 0xb5, 0x90, 0x05, 0x6e, 0x1a, 0x26, 0x58, 0x47, 0x37, 0x30,
	0x89, 0x95, 0x0b, 0x33, 0xfa, 0x0d, 0x69, 0xaa, 0x93, 0xa6, 0x64, 0xf1, 0xa7, 0x7f, 0xef, 0xeb,
	0x34, 0x1d, 0xa2, 0xdc, 0x9f, 0xcf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x39, 0xab, 0x94, 0x19,
	0x03, 0x00, 0x00,
}
