status = [
  "continuous-integration/travis-ci/push",
]

delete_merged_branches = true
use_squash_merge = true

# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
