status = ["ci-status", "systest-status"]

block_labels = [ "do-not-merge-yet" ]
required_approvals = 1
delete_merged_branches = true
update_base_for_deletes = true
use_squash_merge = true
cut_body_after = "## Description"
timeout_sec = 10800            # 3 hours
