status = [
  "continuous-integration/travis-ci/push",
  "systemtest-latenodes",
  "systemtest-blocks-add-node",
  "systemtest-hare-mining",
  "systemtest-sync-blocks",
  "systemtest-genesis-p2p",
]

required_approvals = 1
delete_merged_branches = true
use_squash_merge = true
timeout_sec = 10800  # 3 hours
