# sample spacemesh config file
# use the config flag to start a node with a config file.
# e.g $./go-spacemash --config ./config.toml
# cli flags will get a higher priority than configured in the file.

# Main Config
[main]
data-folder = "~/.spacemesh-data"
test-mode = false
metrics = false
metrics-port = 12020
oracle_server = "http://localhost:3030"
oracle_server_worldid = 0
genesis-time = "2019-02-13T17:02:00+00:00"
layer-duration-sec = "5"
hdist = "5"
coinbase = "0x1234"
golden-atx = "0x5678"

# Node Config
[p2p]
listen = "/ip4/0.0.0.0/tcp/17513"
network-id = 1
target-outbound = 2
bootnodes = [] # example : spacemesh://j7qWfWaJRVp25ZsnCu9rJ4PmhigZBtesB4YmQHqqPvt@0.0.0.0:7517?disc=7517

# API Config
[api]
grpc-server = true
json-server = true
grpc-port = 19092
json-port = 19093

# Time sync NTP Config
[time]
max-allowed-time-drift = "10s"
ntp-queries = 5
default-timeout-latency = "10s"

# Hare Config
[hare]
hare-round-duration-sec = "5"
hare-committee-size = 800
hare-max-adversaries = 399
hare-wakeup-delta = 5

[logging]
app = "info"
post = "info"
stateDb= "info"
state = "info"
atxDbStore = "info"
beacon = "info"
weakCoin = "info"
poetDbStore = "info"
store = "info"
meshDb = "info"
trtl = "info"
block-eligibility = "info"
mesh = "info"
sync = "info"
block-oracle = "info"
hare-oracle = "info"
hare = "info"
block-builder = "info"
block-listener = "info"
poet = "info"
nipost = "info"
atx-builder = "info"
