// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package wire

import (
	"github.com/spacemeshos/go-scale"
)

func (t *InvalidPostIndexProofV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := t.Atx.EncodeScale(enc)
		if err != nil {
			return total, err
		}
		total += n
	}
	{
		n, err := scale.EncodeCompact32(enc, uint32(t.InvalidIdx))
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *InvalidPostIndexProofV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		n, err := t.Atx.DecodeScale(dec)
		if err != nil {
			return total, err
		}
		total += n
	}
	{
		field, n, err := scale.DecodeCompact32(dec)
		if err != nil {
			return total, err
		}
		total += n
		t.InvalidIdx = uint32(field)
	}
	return total, nil
}
