[package]
name = "multisig"
version = "0.1.0"
edition = "2021"

[dependencies]
parity-scale-codec = { version = "3.6.12", features = ["derive"] }
athena-interface = { git = "https://github.com/athenavm/athena", tag = "v0.6.2" }
athena-vm = { git = "https://github.com/athenavm/athena", tag = "v0.6.2" }
athena-vm-declare = { git = "https://github.com/athenavm/athena", tag = "v0.6.2" }
athena-vm-sdk = { git = "https://github.com/athenavm/athena", tag = "v0.6.2" }

[dev-dependencies]
multisig = { path = ".", features = ["unittest"] }
athena-sdk = { git = "https://github.com/athenavm/athena", tag = "v0.6.2" }
athena-runner = { git = "https://github.com/athenavm/athena", tag = "v0.6.2" }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8.5"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
athena-helper = { git = "https://github.com/athenavm/athena", tag = "v0.6.1" }

[features]
unittest = []
