// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package handshake

import (
	"github.com/spacemeshos/go-scale"
)

func (t *HandshakeMessage) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeByteArray(enc, t.GenesisID[:])
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *HandshakeMessage) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		n, err := scale.DecodeByteArray(dec, t.GenesisID[:])
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *HandshakeAck) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeStringWithLimit(enc, string(t.Error), 256)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *HandshakeAck) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeStringWithLimit(dec, 256)
		if err != nil {
			return total, err
		}
		total += n
		t.Error = string(field)
	}
	return total, nil
}
