// Code generated by MockGen. DO NOT EDIT.
// Source: ./activation.go
//
// Generated by this command:
//
//	mockgen -typed -package=v2alpha1 -destination=./activation_mocks.go -source=./activation.go
//

// Package v2alpha1 is a generated GoMock package.
package v2alpha1

import (
	reflect "reflect"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockactivationProvider is a mock of activationProvider interface.
type MockactivationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockactivationProviderMockRecorder
	isgomock struct{}
}

// MockactivationProviderMockRecorder is the mock recorder for MockactivationProvider.
type MockactivationProviderMockRecorder struct {
	mock *MockactivationProvider
}

// NewMockactivationProvider creates a new mock instance.
func NewMockactivationProvider(ctrl *gomock.Controller) *MockactivationProvider {
	mock := &MockactivationProvider{ctrl: ctrl}
	mock.recorder = &MockactivationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockactivationProvider) EXPECT() *MockactivationProviderMockRecorder {
	return m.recorder
}

// GetAtx mocks base method.
func (m *MockactivationProvider) GetAtx(id types.ATXID) (*types.ActivationTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAtx", id)
	ret0, _ := ret[0].(*types.ActivationTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAtx indicates an expected call of GetAtx.
func (mr *MockactivationProviderMockRecorder) GetAtx(id any) *MockactivationProviderGetAtxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAtx", reflect.TypeOf((*MockactivationProvider)(nil).GetAtx), id)
	return &MockactivationProviderGetAtxCall{Call: call}
}

// MockactivationProviderGetAtxCall wrap *gomock.Call
type MockactivationProviderGetAtxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockactivationProviderGetAtxCall) Return(arg0 *types.ActivationTx, arg1 error) *MockactivationProviderGetAtxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockactivationProviderGetAtxCall) Do(f func(types.ATXID) (*types.ActivationTx, error)) *MockactivationProviderGetAtxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockactivationProviderGetAtxCall) DoAndReturn(f func(types.ATXID) (*types.ActivationTx, error)) *MockactivationProviderGetAtxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MaxHeightAtx mocks base method.
func (m *MockactivationProvider) MaxHeightAtx() (types.ATXID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxHeightAtx")
	ret0, _ := ret[0].(types.ATXID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MaxHeightAtx indicates an expected call of MaxHeightAtx.
func (mr *MockactivationProviderMockRecorder) MaxHeightAtx() *MockactivationProviderMaxHeightAtxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxHeightAtx", reflect.TypeOf((*MockactivationProvider)(nil).MaxHeightAtx))
	return &MockactivationProviderMaxHeightAtxCall{Call: call}
}

// MockactivationProviderMaxHeightAtxCall wrap *gomock.Call
type MockactivationProviderMaxHeightAtxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockactivationProviderMaxHeightAtxCall) Return(arg0 types.ATXID, arg1 error) *MockactivationProviderMaxHeightAtxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockactivationProviderMaxHeightAtxCall) Do(f func() (types.ATXID, error)) *MockactivationProviderMaxHeightAtxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockactivationProviderMaxHeightAtxCall) DoAndReturn(f func() (types.ATXID, error)) *MockactivationProviderMaxHeightAtxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
