apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth-10mpbs
spec:
  action: bandwidth
  mode: all
  selector:
    expressionSelectors:
      - key: app
        operator: In
        values: ["boot", "smesher"]
  direction: to
  bandwidth:
    rate: "10mbps"
    limit: 20971520
    buffer: 1048576