apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: positive-offset
spec:
  mode: all
  selector:
    expressionSelectors:
      - key: bucket
        operator: In
        values: ["4"]
  timeOffset: '400ms'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: negative-offset
spec:
  mode: all
  selector:
    expressionSelectors:
      - key: bucket
        operator: In
        values: ["5"]
  timeOffset: '-400ms'