// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

/*
Package p2p is a generated protocol buffer package.

It is generated from these files:
	p2p.proto

It has these top-level messages:
	MessageData
	PingRequest
	PingResponse
	EchoRequest
	EchoResponse
*/
package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion string `protobuf:"bytes,1,opt,name=clientVersion" json:"clientVersion,omitempty"`
	Timestamp     int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Id            string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Gossip        bool   `protobuf:"varint,4,opt,name=gossip" json:"gossip,omitempty"`
	NodeId        string `protobuf:"bytes,5,opt,name=nodeId" json:"nodeId,omitempty"`
	NodePubKey    []byte `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign          string `protobuf:"bytes,7,opt,name=sign" json:"sign,omitempty"`
}

func (m *MessageData) Reset()                    { *m = MessageData{} }
func (m *MessageData) String() string            { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()               {}
func (*MessageData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

// a protocol define a set of reuqest and responses
type PingRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	// method specific data
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	// response specific data
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// a protocol define a set of reuqest and responses
type EchoRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	// method specific data
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EchoRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	// response specific data
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EchoResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageData)(nil), "p2p.MessageData")
	proto.RegisterType((*PingRequest)(nil), "p2p.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "p2p.PingResponse")
	proto.RegisterType((*EchoRequest)(nil), "p2p.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "p2p.EchoResponse")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xa4, 0xa6, 0x66, 0xb6, 0x8a, 0xcc, 0x41, 0xf6, 0x20, 0x12, 0x82, 0x87, 0x9c,
	0x7a, 0x88, 0x7f, 0x41, 0x0f, 0x22, 0x42, 0xd9, 0x83, 0x97, 0x7a, 0x49, 0x9b, 0x21, 0x2e, 0x98,
	0xdd, 0xb5, 0xb3, 0x3d, 0xf8, 0x03, 0xfd, 0x5f, 0x92, 0x6d, 0xa4, 0xf1, 0x6e, 0x6f, 0xf3, 0x1e,
	0x33, 0x8f, 0xf7, 0xc1, 0x40, 0xee, 0x6b, 0xbf, 0xf4, 0x3b, 0x17, 0x1c, 0xa6, 0xbe, 0xf6, 0xe5,
	0xb7, 0x00, 0xf9, 0x42, 0xcc, 0x4d, 0x47, 0x0f, 0x4d, 0x68, 0xf0, 0x0e, 0x2e, 0xb6, 0x1f, 0x86,
	0x6c, 0x78, 0xa5, 0x1d, 0x1b, 0x67, 0x95, 0x28, 0x44, 0x95, 0xeb, 0xbf, 0x26, 0xde, 0x40, 0x1e,
	0x4c, 0x4f, 0x1c, 0x9a, 0xde, 0xab, 0xa4, 0x10, 0x55, 0xaa, 0x8f, 0x06, 0x5e, 0x42, 0x62, 0x5a,
	0x95, 0xc6, 0xc3, 0xc4, 0xb4, 0x78, 0x0d, 0x59, 0xe7, 0x98, 0x8d, 0x57, 0xb3, 0x42, 0x54, 0xe7,
	0x7a, 0x54, 0x83, 0x6f, 0x5d, 0x4b, 0x4f, 0xad, 0x3a, 0x8b, 0xbb, 0xa3, 0xc2, 0x5b, 0x80, 0x61,
	0x5a, 0xed, 0x37, 0xcf, 0xf4, 0xa5, 0xb2, 0x42, 0x54, 0x0b, 0x3d, 0x71, 0x10, 0x61, 0xc6, 0xa6,
	0xb3, 0x6a, 0x1e, 0xaf, 0xe2, 0x5c, 0xae, 0x41, 0xae, 0x8c, 0xed, 0x34, 0x7d, 0xee, 0x89, 0x03,
	0xd6, 0x20, 0xfb, 0x23, 0x55, 0x84, 0x90, 0xf5, 0xd5, 0x72, 0x80, 0x9f, 0xd0, 0xea, 0xe9, 0x12,
	0x2a, 0x98, 0x8f, 0x32, 0x22, 0xe5, 0xfa, 0x57, 0x96, 0x6f, 0xb0, 0x38, 0x84, 0xb3, 0x77, 0x96,
	0xe9, 0x9f, 0xd3, 0xd7, 0x20, 0x1f, 0xb7, 0xef, 0xee, 0x64, 0xd5, 0x0f, 0xe1, 0xa7, 0xa8, 0xbe,
	0xc9, 0xe2, 0x27, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x10, 0xdb, 0x97, 0x56, 0x02,
	0x00, 0x00,
}
