// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	SimpleMessage
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleMessage struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *SimpleMessage) Reset()                    { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string            { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()               {}
func (*SimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SimpleMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "pb.SimpleMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SpaceMeshService service

type SpaceMeshServiceClient interface {
	Echo(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (*SimpleMessage, error)
}

type spaceMeshServiceClient struct {
	cc *grpc.ClientConn
}

func NewSpaceMeshServiceClient(cc *grpc.ClientConn) SpaceMeshServiceClient {
	return &spaceMeshServiceClient{cc}
}

func (c *spaceMeshServiceClient) Echo(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (*SimpleMessage, error) {
	out := new(SimpleMessage)
	err := grpc.Invoke(ctx, "/pb.SpaceMeshService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SpaceMeshService service

type SpaceMeshServiceServer interface {
	Echo(context.Context, *SimpleMessage) (*SimpleMessage, error)
}

func RegisterSpaceMeshServiceServer(s *grpc.Server, srv SpaceMeshServiceServer) {
	s.RegisterService(&_SpaceMeshService_serviceDesc, srv)
}

func _SpaceMeshService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceMeshServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SpaceMeshService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceMeshServiceServer).Echo(ctx, req.(*SimpleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpaceMeshService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SpaceMeshService",
	HandlerType: (*SpaceMeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _SpaceMeshService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf,
	0x2b, 0x86, 0xa8, 0x50, 0x52, 0xe5, 0xe2, 0x0d, 0xce, 0xcc, 0x2d, 0xc8, 0x49, 0xf5, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x8c, 0x62, 0xb9, 0x04, 0x82, 0x0b, 0x12, 0x93, 0x41, 0xaa,
	0x32, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x3c, 0xb9, 0x58, 0x5c, 0x93, 0x33, 0xf2,
	0x85, 0x04, 0xf5, 0x0a, 0x92, 0xf4, 0x50, 0x0c, 0x91, 0xc2, 0x14, 0x52, 0x92, 0x6e, 0xba, 0xfc,
	0x64, 0x32, 0x93, 0xa8, 0x92, 0x80, 0x7e, 0x99, 0xa1, 0x7e, 0x6a, 0x45, 0x22, 0x48, 0x4e, 0x3f,
	0x35, 0x39, 0x23, 0xdf, 0x8a, 0x51, 0x2b, 0x89, 0x0d, 0xec, 0x18, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x55, 0xc8, 0xa8, 0x97, 0xbb, 0x00, 0x00, 0x00,
}
