// Code generated by MockGen. DO NOT EDIT.
// Source: ./vm.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/spacemeshos/go-spacemesh/common/types"
)

// MockValidationRequest is a mock of ValidationRequest interface.
type MockValidationRequest struct {
	ctrl     *gomock.Controller
	recorder *MockValidationRequestMockRecorder
}

// MockValidationRequestMockRecorder is the mock recorder for MockValidationRequest.
type MockValidationRequestMockRecorder struct {
	mock *MockValidationRequest
}

// NewMockValidationRequest creates a new mock instance.
func NewMockValidationRequest(ctrl *gomock.Controller) *MockValidationRequest {
	mock := &MockValidationRequest{ctrl: ctrl}
	mock.recorder = &MockValidationRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationRequest) EXPECT() *MockValidationRequestMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockValidationRequest) Parse() (*types.TxHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse")
	ret0, _ := ret[0].(*types.TxHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockValidationRequestMockRecorder) Parse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockValidationRequest)(nil).Parse))
}

// Verify mocks base method.
func (m *MockValidationRequest) Verify() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockValidationRequestMockRecorder) Verify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockValidationRequest)(nil).Verify))
}
