version: "3"

services:
  activation-service:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:e5ee083f7
    command:
      [
        "-c",
        "/config.json",
        "--node-service-address",
        "http://127.0.0.1:9099",
        "--grpc-json-listener",
        "0.0.0.0:9071",
        "--proxy-api-v2-address",
        "http://127.0.0.1:9060",
        "--proxy-listener",
        "0.0.0.0:9072",
        "--grpc-public-listener",
        "0.0.0.0:9082",
        "--grpc-private-listener",
        "0.0.0.0:9083",
      ]
    volumes:
      - ./spacemesh-client:/tmp/spacemesh-client
      - ./config.testnet.client.merged.json:/config.json
    ports:
      - 9071:9071
      - 9072:9072
      - 9082:9082
      - 9083:9083

    # networks:
    #   - spacemesh-testnet

  node-service:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:e5ee083f7
    command: [
        "-c",
        "/config.json",
        "--grpc-json-listener",
        "0.0.0.0:9060",
        "--grpc-public-listener",
        "0.0.0.0:9062",
        "--grpc-private-listener",
        "0.0.0.0:9063",
        # "--node-service-listener",
        # "0.0.0.0:9099", ## this is somehow not exposed via CLI
      ]
    volumes:
      - ./spacemesh-node-service:/tmp/spacemesh-node-service
      - ./config.testnet.node-service.merged.json:/config.json
    # networks:
    #   - spacemesh-testnet
    ports:
      - 9062:9062
      - 9063:9063
      - 9060:9060
      - 9099:9099
# networks:
#   spacemesh-testnet:
#     driver: host
