version: '3'

services:
  activation-service:
    image: ${IMAGE}
    command: [
      "smeshing",
      "-c", "/config.json",
      "--node-service-address", "http://node-service:9099",
      "--grpc-json-listener", "0.0.0.0:9071",
      "--proxy-api-v2-address", "http://node-service:9070",
      "--json-cors-everywhere"
    ]
    volumes:
      - /tmp/spacemesh-client:/tmp/spacemesh-client
      - ./config.standalone.client.json:/config.json
    ports:
      - 9071:9071
    networks:
      - spacemesh-net

  node-service:
    image: ${IMAGE}
    command: [
      "-c", "/config.json",
      "--grpc-json-listener", "0.0.0.0:9070",
    ]
    volumes:
      - /tmp/spacemesh-node-service:/tmp/spacemesh-node-service
      - ./config.standalone.node-service.json:/config.json
    networks:
      - spacemesh-net
    ports:
      - 9092:9092
      - 9093:9093

networks:
  spacemesh-net:
    driver: bridge
