version: '3'

services:
  activation-service:
    image: ${IMAGE}
    command: [
      "-c", "/config.json",
      "--node-service-address", "http://node-service:9099",
      "--grpc-json-listener", "0.0.0.0:9071",
      "--proxy-api-v2-address", "http://node-service:9070",
      "--proxy-listener", "0.0.0.0:9072"
    ]
#    ports:
#        - "9071:9071"
#        - "9072:9072"
    volumes:
      - /tmp/spacemesh-client:/tmp/spacemesh-client
      - ./config.standalone.client.json:/config.json
    networks:
      - spacemesh-net

  node-service:
    image: ${IMAGE}
    command: ["-c", "/config.json", "--smeshing-opts-datadir", "/tmp/spacemesh-node-post",
              "--grpc-json-listener", "0.0.0.0:9070"]
    volumes:
      - /tmp/spacemesh-node-service:/tmp/spacemesh-node-service
      - ./config.standalone.node-service.json:/config.json
    networks:
      - spacemesh-net

networks:
  spacemesh-net:
    driver: bridge
