services:
  activation-service-remote-1:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:2c898bb30
    command:
      [
        "-c",
        "/config.json",
        "--node-service-address",
        "http://testnet-16-node-service.spacemesh.network:9099",
        "--grpc-json-listener",
        "0.0.0.0:19071",
        "--proxy-api-v2-address",
        "http://testnet-16-node-service.spacemesh.network",
        "--grpc-public-listener",
        "0.0.0.0:19082",
        "--grpc-private-listener",
        "0.0.0.0:19083",
        "--json-cors-everywhere",
      ]
    volumes:
      - ./spacemesh-client-remote-1:/tmp/spacemesh-client
      - ./config.testnet-16-smesher-service.json:/config.json

  activation-service-remote-2:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:2c898bb30
    command:
      [
        "-c",
        "/config.json",
        "--node-service-address",
        "http://testnet-16-node-service.spacemesh.network:9099",
        "--grpc-json-listener",
        "0.0.0.0:19171",
        "--proxy-api-v2-address",
        "http://testnet-16-node-service.spacemesh.network",
        "--grpc-public-listener",
        "0.0.0.0:19182",
        "--grpc-private-listener",
        "0.0.0.0:19183",
        "--json-cors-everywhere",
      ]
    volumes:
      - ./spacemesh-client-remote-2:/tmp/spacemesh-client
      - ./config.testnet-16-smesher-service.json:/config.json
