services:
  activation-service-local-1:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:2c898bb30
    command:
      [
        "-c",
        "/config.json",
        "--node-service-address",
        "http://127.0.0.1:19099",
        "--grpc-json-listener",
        "0.0.0.0:19171",
        "--proxy-api-v2-address",
        "http://127.0.0.1:19060",
        "--grpc-public-listener",
        "0.0.0.0:19282",
        "--grpc-private-listener",
        "0.0.0.0:19283",
        "--json-cors-everywhere",
      ]
    volumes:
      - ./spacemesh-client-local-1:/tmp/spacemesh-client
      - ./config.testnet-16-smesher-service.json:/config.json
    ports:
      - 19271:19271
      - 19272:19272
      - 19282:19222
      - 19283:19283

  activation-service-local-2:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:2c898bb30
    command:
      [
        "-c",
        "/config.json",
        "--node-service-address",
        "http://127.0.0.1:19399",
        "--grpc-json-listener",
        "0.0.0.0:19371",
        "--proxy-api-v2-address",
        "http://127.0.0.1:19060",
        "--grpc-public-listener",
        "0.0.0.0:19382",
        "--grpc-private-listener",
        "0.0.0.0:19383",
        "--json-cors-everywhere",
      ]
    volumes:
      - ./spacemesh-client-local-2:/tmp/spacemesh-client
      - ./config.testnet-16-smesher-service.json:/config.json
    ports:
      - 19371:19371
      - 19372:19372
      - 19382:19382
      - 19383:19383

  node-service-local:
    network_mode: "host"
    image: spacemeshos/go-spacemesh-dev:2c898bb30
    command: [
        "-c",
        "/config.json",
        "--grpc-json-listener",
        "0.0.0.0:19060",
        "--grpc-public-listener",
        "0.0.0.0:19062",
        "--grpc-private-listener",
        "0.0.0.0:19063",
        # "--node-service-listener",
        # "0.0.0.0:19099", ## this is not exposed via CLI
      ]
    volumes:
      - ./spacemesh-node-service-multi:/tmp/spacemesh-node-service
      - ./config.testnet.node-service.json:/config.json
    ports:
      - 19062:19062
      - 19063:19063
      - 19060:19060
      - 19099:19099
