// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spacemeshos/go-spacemesh/api (interfaces: NetworkIdentity,AtxProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	peer "github.com/libp2p/go-libp2p/core/peer"
	types "github.com/spacemeshos/go-spacemesh/common/types"
)

// MockNetworkIdentity is a mock of NetworkIdentity interface.
type MockNetworkIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkIdentityMockRecorder
}

// MockNetworkIdentityMockRecorder is the mock recorder for MockNetworkIdentity.
type MockNetworkIdentityMockRecorder struct {
	mock *MockNetworkIdentity
}

// NewMockNetworkIdentity creates a new mock instance.
func NewMockNetworkIdentity(ctrl *gomock.Controller) *MockNetworkIdentity {
	mock := &MockNetworkIdentity{ctrl: ctrl}
	mock.recorder = &MockNetworkIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkIdentity) EXPECT() *MockNetworkIdentityMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *MockNetworkIdentity) ID() peer.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(peer.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockNetworkIdentityMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockNetworkIdentity)(nil).ID))
}

// MockAtxProvider is a mock of AtxProvider interface.
type MockAtxProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAtxProviderMockRecorder
}

// MockAtxProviderMockRecorder is the mock recorder for MockAtxProvider.
type MockAtxProviderMockRecorder struct {
	mock *MockAtxProvider
}

// NewMockAtxProvider creates a new mock instance.
func NewMockAtxProvider(ctrl *gomock.Controller) *MockAtxProvider {
	mock := &MockAtxProvider{ctrl: ctrl}
	mock.recorder = &MockAtxProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAtxProvider) EXPECT() *MockAtxProviderMockRecorder {
	return m.recorder
}

// GetFullAtx mocks base method.
func (m *MockAtxProvider) GetFullAtx(arg0 types.ATXID) (*types.VerifiedActivationTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullAtx", arg0)
	ret0, _ := ret[0].(*types.VerifiedActivationTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullAtx indicates an expected call of GetFullAtx.
func (mr *MockAtxProviderMockRecorder) GetFullAtx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullAtx", reflect.TypeOf((*MockAtxProvider)(nil).GetFullAtx), arg0)
}
